<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Confidence-Intervals" data-toc-modified-id="Confidence-Intervals-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Confidence Intervals</a></span><ul class="toc-item"><li><span><a href="#Challenge-1" data-toc-modified-id="Challenge-1-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Challenge 1</a></span></li><li><span><a href="#Challenge-2" data-toc-modified-id="Challenge-2-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Challenge 2</a></span></li><li><span><a href="#Challenge-3---More-practice" data-toc-modified-id="Challenge-3---More-practice-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Challenge 3 - More practice</a></span></li><li><span><a href="#Challenge-4---More-practice" data-toc-modified-id="Challenge-4---More-practice-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Challenge 4 - More practice</a></span></li><li><span><a href="#Bonus-Challenge" data-toc-modified-id="Bonus-Challenge-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Bonus Challenge</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#1.--Determine-what-size-the-selected-sample-of-men-should-be." data-toc-modified-id="1.--Determine-what-size-the-selected-sample-of-men-should-be.-1.5.0.1"><span class="toc-item-num">1.5.0.1&nbsp;&nbsp;</span>1.- Determine what size the selected sample of men should be.</a></span></li><li><span><a href="#2.--For-the-second-challenge,-we-have-the-following-error:" data-toc-modified-id="2.--For-the-second-challenge,-we-have-the-following-error:-1.5.0.2"><span class="toc-item-num">1.5.0.2&nbsp;&nbsp;</span>2.- For the second challenge, we have the following error:</a></span></li><li><span><a href="#Determine-the-sample-size-required-to-not-exceed-an-error-of-1%-with-a-confidence-of-80%." data-toc-modified-id="Determine-the-sample-size-required-to-not-exceed-an-error-of-1%-with-a-confidence-of-80%.-1.5.0.3"><span class="toc-item-num">1.5.0.3&nbsp;&nbsp;</span>Determine the sample size required to not exceed an error of 1% with a confidence of 80%.</a></span></li></ul></li></ul></li><li><span><a href="#Bonus-Challenge" data-toc-modified-id="Bonus-Challenge-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Bonus Challenge</a></span></li></ul></li></ul></div>

# Confidence Intervals

In [2]:
# Libraries
import pandas as pd
import numpy as np
import scipy.stats as st
import statistics

## Challenge 1
We want to estimate the average size of the men of a country with a confidence level of 80%. Assuming that the standard deviation of the sizes in the population is 4, get the confidence interval with a sample of men selected randomly, whose heights are:

````
heights = [167, 167, 168, 168, 168, 169, 171, 172, 173, 175, 175, 175, 177, 182, 195]
````

**Hint**: function `stats.norm.interval` from `scipy` can help you get through this exercise. 

In [12]:
# your code herest.t.interval(alpha=0.95, df=len(data)-1, loc=np.mean(data), scale=st.sem(data)) 
#stats.norm.interval(.95, loc = 175, scale = 20/np.sqrt(40))
#from scipy import stats.norm.interval
heights = [167, 167, 168, 168, 168, 169, 171, 172, 173, 175, 175, 175, 177, 182, 195]

st.norm.interval(.8, loc=np.mean(heights), scale=4)

(168.34046040448825, 178.59287292884508)

## Challenge 2 
In a sample of 105 shops selected randomly from an area, we note that 27 of them have had losses in this month. Get an interval for the proportion of businesses in the area with losses to a confidence level of 80% and a confidence level of 90%.

**Hint**: function `stats.norm.interval` from `scipy` can help you get through this exercise. 

In [14]:

# Function for computing confidence intervals
import statsmodels.api as sm
from statsmodels.stats.proportion import proportion_confint   
print('sample proportion, ', 27/105)
proportion_confint(count=27,    # Number of "successes"
                   nobs=105,    # Number of trials
                   alpha=(1 - 0.8))

sample proportion,  0.2571428571428571


(0.20248138545542083, 0.3118043288302934)

In [15]:
print('sample proportion, ', 27/105)
proportion_confint(count=27,    # Number of "successes"
                   nobs=105,    # Number of trials
                   alpha=(1 - 0.9))

sample proportion,  0.2571428571428571


(0.1869856177645281, 0.32730009652118613)

## Challenge 3 - More practice
For the same example in challenge 1, calculate a confidence interval for the variance at 90% level.

**Hint**: function `stats.chi2.interval` from `scipy` can help you get through this exercise. 

In [20]:
#  location is the mean and the scale is the standard deviation.
heights = [167, 167, 168, 168, 168, 169, 171, 172, 173, 175, 175, 175, 177, 182, 195]

st.chi2.interval(0.05, heights, loc=np.mean(heights), scale=4)

(array([834.2390265 , 834.2390265 , 838.22527913, 838.22527913,
        838.22527913, 842.2115729 , 850.18428241, 854.17069743,
        858.15715216, 866.13017935, 866.13017935, 866.13017935,
        874.10336128, 894.03697595, 945.86855006]),
 array([843.38573994, 843.38573994, 847.39946462, 847.39946462,
        847.39946462, 851.41314843, 859.44039488, 863.45395822,
        867.46748211, 875.49441288, 875.49441288, 875.49441288,
        883.52118987, 903.58747646, 955.75566942]))

## Challenge 4 - More practice
The sulfuric acid content of 7 similar containers is 9.8, 10.2, 10.4, 9.8, 10.0, 10.2 and 9.6 liters. Calculate a 95% confidence interval for the average content of all containers assuming an approximately normal distribution.

```
acid = [9.8, 10.2, 10.4, 9.8, 10.0, 10.2, 9.6]
```

**Hint**: function `stats.t.interval` from `scipy` can help you get through this exercise. 

In [22]:
# your code hereinterval(alpha, df, loc=0, scale=1)
acid = [9.8, 10.2, 10.4, 9.8, 10.0, 10.2, 9.6]
CL = .95
alpha = (1-CL)/2
st.t.interval(alpha, acid, loc=np.mean(acid), scale=1)

(array([9.96785286, 9.96788488, 9.96789996, 9.96785286, 9.96786919,
        9.96788488, 9.96783584]),
 array([10.03214714, 10.03211512, 10.03210004, 10.03214714, 10.03213081,
        10.03211512, 10.03216416]))

## Bonus Challenge
The error level or sampling error for the first challenge is given by the following expression:
$$Error = z_{\frac{\alpha}{2}}\frac{\sigma}{\sqrt n}$$
Where z represents the value for N(0,1)


Suppose that with the previous data of challenge 1, and with a confidence level of
99% (that is, almost certainly) we want to estimate the average population size, so that the error level committed is not greater than half a centimeter.

#### 1.- Determine what size the selected sample of men should be.

In [ ]:
# your code here

#### 2.- For the second challenge, we have the following error:
$$ Error = z_{\frac{\alpha}{2}}\sqrt{\frac{p\times q}{n}} $$
#### Determine the sample size required to not exceed an error of 1% with a confidence of 80%.

In [ ]:
# your code here

## Bonus Challenge

Let's consider the following problem:

Build a confidence interval of 94% for the real difference between the durations of two brands of spotlights, if a sample of 40 spotlights taken randomly from the first mark gave an average duration of 418 hours, and a sample of 50 bulbs of another brand gave a duration average of 402 hours. The standard deviations of the two
populations are 26 hours and 22 hours, respectively.

Sometimes, we will be interested in the difference of two different groups of random variables. We can also build a confidence interval for that! We have some different cases regarding the variance but for this specific case (the variance are different and known), we have that:

$$\overline{X} - \overline{Y}  \sim N(\mu_{X} - \mu_{Y} , \sqrt{\frac{\sigma_{X}^2}{n_X}+\frac{\sigma_{Y}^2}{n_Y}})$$

Solve the problem with this information.

In [ ]:
# your code here