# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [12]:
# your code here
import numpy as np
from numpy import random

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.20.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a=np.random.random((2,3,5))
a

array([[[0.9223627 , 0.4531243 , 0.37575015, 0.89446468, 0.03327967],
        [0.24512661, 0.21054115, 0.69995313, 0.23050532, 0.26015834],
        [0.28747028, 0.59554672, 0.98101316, 0.7503212 , 0.89019755]],

       [[0.26996113, 0.63131785, 0.84427982, 0.80023048, 0.074445  ],
        [0.05967467, 0.54413571, 0.28322345, 0.32983177, 0.09093087],
        [0.32656088, 0.23855964, 0.29773692, 0.31689692, 0.2894397 ]]])

In [7]:
# Method 2
rg = np.random.default_rng(1) #limited by 1
b = rg.random((2,3,5)) #dimensions of matrix
b

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [14]:
# Method 3
c = random.randint(10, size=(2,3,5))
c

array([[[6, 6, 2, 5, 0],
        [2, 3, 9, 4, 8],
        [4, 9, 8, 0, 9]],

       [[7, 9, 2, 2, 7],
        [9, 0, 8, 3, 7],
        [4, 0, 8, 4, 5]]])

#### 4. Print *a*.


In [15]:
# your code here
print(a)

[[[0.9223627  0.4531243  0.37575015 0.89446468 0.03327967]
  [0.24512661 0.21054115 0.69995313 0.23050532 0.26015834]
  [0.28747028 0.59554672 0.98101316 0.7503212  0.89019755]]

 [[0.26996113 0.63131785 0.84427982 0.80023048 0.074445  ]
  [0.05967467 0.54413571 0.28322345 0.32983177 0.09093087]
  [0.32656088 0.23855964 0.29773692 0.31689692 0.2894397 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.ones((5, 2, 3), dtype=np.int16)

#### 6. Print *b*.


In [30]:
# your code here
print(b)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
# your code here
if a.size == b.size:
    print("same size", a.size)

same size 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
# We can't because they have different shapes
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [32]:
# your code here
c= b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [33]:
# your code/ It works because the arrays have the same shape
d = a + c
d

array([[[1.9223627 , 1.4531243 , 1.37575015, 1.89446468, 1.03327967],
        [1.24512661, 1.21054115, 1.69995313, 1.23050532, 1.26015834],
        [1.28747028, 1.59554672, 1.98101316, 1.7503212 , 1.89019755]],

       [[1.26996113, 1.63131785, 1.84427982, 1.80023048, 1.074445  ],
        [1.05967467, 1.54413571, 1.28322345, 1.32983177, 1.09093087],
        [1.32656088, 1.23855964, 1.29773692, 1.31689692, 1.2894397 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [38]:
# your code/ d = a + c and c had only 1 in values donc a = d + 1
print('a',a)
print('\n')
print('d',d)

a [[[0.9223627  0.4531243  0.37575015 0.89446468 0.03327967]
  [0.24512661 0.21054115 0.69995313 0.23050532 0.26015834]
  [0.28747028 0.59554672 0.98101316 0.7503212  0.89019755]]

 [[0.26996113 0.63131785 0.84427982 0.80023048 0.074445  ]
  [0.05967467 0.54413571 0.28322345 0.32983177 0.09093087]
  [0.32656088 0.23855964 0.29773692 0.31689692 0.2894397 ]]]


d [[[1.9223627  1.4531243  1.37575015 1.89446468 1.03327967]
  [1.24512661 1.21054115 1.69995313 1.23050532 1.26015834]
  [1.28747028 1.59554672 1.98101316 1.7503212  1.89019755]]

 [[1.26996113 1.63131785 1.84427982 1.80023048 1.074445  ]
  [1.05967467 1.54413571 1.28322345 1.32983177 1.09093087]
  [1.32656088 1.23855964 1.29773692 1.31689692 1.2894397 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [39]:
# your code here
e = a * c
e

array([[[0.9223627 , 0.4531243 , 0.37575015, 0.89446468, 0.03327967],
        [0.24512661, 0.21054115, 0.69995313, 0.23050532, 0.26015834],
        [0.28747028, 0.59554672, 0.98101316, 0.7503212 , 0.89019755]],

       [[0.26996113, 0.63131785, 0.84427982, 0.80023048, 0.074445  ],
        [0.05967467, 0.54413571, 0.28322345, 0.32983177, 0.09093087],
        [0.32656088, 0.23855964, 0.29773692, 0.31689692, 0.2894397 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [40]:
# your code
# yes because we multiplied a by 1 values
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [45]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
d_mean

1.4409013253486678

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [46]:
# your code here
f = np.empty([2, 3, 5])
f

array([[[0.9223627 , 0.4531243 , 0.37575015, 0.89446468, 0.03327967],
        [0.24512661, 0.21054115, 0.69995313, 0.23050532, 0.26015834],
        [0.28747028, 0.59554672, 0.98101316, 0.7503212 , 0.89019755]],

       [[0.26996113, 0.63131785, 0.84427982, 0.80023048, 0.074445  ],
        [0.05967467, 0.54413571, 0.28322345, 0.32983177, 0.09093087],
        [0.32656088, 0.23855964, 0.29773692, 0.31689692, 0.2894397 ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] == d_min:
                f[x][y][z] = 0
            elif d[x][y][z] == d_max:
                f[x][y][z] = 100
            elif d[x][y][z] < d_mean:
                f[x][y][z] = 25
            elif d[x][y][z] > d_mean:
                f[x][y][z] = 75
            else:
                f[x][y][z] = 50
                
f
            

array([[[ 75.,  75.,  25.,  75.,   0.],
        [ 25.,  25.,  75.,  25.,  25.],
        [ 25.,  75., 100.,  75.,  75.]],

       [[ 25.,  75.,  75.,  75.,  25.],
        [ 25.,  75.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [51]:
# your code here
print('d',d)
print('\n')
print('f',f)

d [[[1.9223627  1.4531243  1.37575015 1.89446468 1.03327967]
  [1.24512661 1.21054115 1.69995313 1.23050532 1.26015834]
  [1.28747028 1.59554672 1.98101316 1.7503212  1.89019755]]

 [[1.26996113 1.63131785 1.84427982 1.80023048 1.074445  ]
  [1.05967467 1.54413571 1.28322345 1.32983177 1.09093087]
  [1.32656088 1.23855964 1.29773692 1.31689692 1.2894397 ]]]


f [[[ 75.  75.  25.  75.   0.]
  [ 25.  25.  75.  25.  25.]
  [ 25.  75. 100.  75.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [53]:
# your code here
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] == d_min:
                f[x][y][z] = str("A")
            elif d[x][y][z] == d_max:
                f[x][y][z] = str("E")
            elif d[x][y][z] < d_mean:
                f[x][y][z] = str("B")
            elif d[x][y][z] > d_mean:
                f[x][y][z] = str("D")
            else:
                f[x][y][z] = str("C")
                
f

ValueError: could not convert string to float: 'D'